version: "3.8"

services:
  postgres:
    container_name: inventory_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inventory_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: joaquimgmess21@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - inventory_network

  backend:
    container_name: inventory_backend
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/inventory_db
      NODE_ENV: production
      PORT: 3000
      HOST: "0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inventory_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  inventory_network:
    driver: bridge

volumes:
  postgres_data:
